version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    expose:
      - "3000"
    ports:
      - "4000:3000"
    command: >
      bash -c "yarn install && yarn dev --port=3000"
    networks:
      - psychic-fe
networks:
  psychic-fe:
    # name: psychic_network
    driver: bridge
