version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    platform: linux/arm64/v8
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ && npm start"
    networks:
      - psychic-fe
networks:
  psychic-fe:
    name: psychic_network
    driver: bridge
